cloud:
  aws:
    credentials:
      access-key: AKIA3QHSE7XHG3LJQ5XG
      secret-key: 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
    region:
      static: ap-northeast-2
    s3:
      bucket: imagescollect
    stack:
      auto: false

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB