cloud:
  aws:
    credentials:
      access-key: AKIATXFPQ572E5KULSFJ
      secret-key: 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
    region:
      static: ap-northeast-2
    s3:
      bucket: jack-image
    stack:
      auto: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clone?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: jachky1205
    password: hicode119!!
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB



#  spring.datasource.url=
#  spring.datasource.username=jachky1205
#  spring.datasource.password=hicode119!!
#  spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
